# permissions for end users to edit controllers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: controller-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-1-controller
    app.kubernetes.io/part-of: test-1-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-editor-role
rules:
- apiGroups:
  - delivery.controller-e2e-framework
  resources:
  - controllers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.controller-e2e-framework
  resources:
  - controllers/status
  verbs:
  - get
